### PR TITLE
auth-handler unit tests

### PR DESCRIPTION
**Pull request by almeida-shrutika**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=keHf4t0)

Ticket Number: CS-38880, CS-38881
No Version Bump

### CODE REVIEW

**Comment by netrajpatel** [comment]
Hi @almeida-shrutika,
Can you please update the ticket number and version bump details in the PR's description?

**Comment by almeida-shrutika** [comment]
> Hi @almeida-shrutika, Can you please update the ticket number and version bump details in the PR's description?

Done

**Comment by almeida-shrutika** [comment]
> Hi @almeida-shrutika, Can you please update the ticket number and version bump details in the PR's description?

Done

**Comment by netrajpatel** [comment]
@almeida-shrutika Can you merge the latest development changes in this branch?

**Comment by almeida-shrutika** [comment]
> @almeida-shrutika Can you merge the latest development changes in this branch?
@netrajpatel done

**Pull request merged**
