### PR TITLE
fix(bootstrap): handled github rate limit error

### PR DESCRIPTION
**Pull request by vkalta**
This PR fixes CS-32661.

### CODE REVIEW

**Comment by shafeeqd959** [comment]
@vkalta , if client request has been exceeded the limit, its better show a custom message rather than showing whats coming from github. Message can be informing the user that he/she exceeded the number of request and suggest the user to run the command after the limited time (one hour or whatever time it is).

**Comment by vkalta** [comment]
Screenshot 2023-01-12 at 15 31 35
@shafeeqd959 @antonyagustine An appropriate message is added to response.
cc: @netrajpatel

**Comment by netrajpatel** [comment]
Hi @vkalta,
The above suggestions given by @shafeeqd959 and @antonyagustine are specific to showing our own custom message rather than showing the message received from GitHub's end.
Is it feasible to show the below message - 
`Request limit exceeded. Please try again after 60 minutes.`
(@vkalta You can modify the above message for the exact number of minutes to retry)

**Comment by vkalta** [comment]
Screenshot 2023-01-13 at 15 59 55
@netrajpatel Changes added.

**Review by netrajpatel — APPROVED** [review]

**Pull request merged**
