### PR TITLE
refactor: export marketplace apps HTTP adapter calls to SDK call migration [CS-42903]

### PR DESCRIPTION
**Pull request by antonyagustine**
**CS-42903**
- [x] refactor: export marketplace apps HTTP adapter calls to SDK call migration.
- [x] test: Unit test cases updated as per the HTTP calls to SDK Migration.

**NOTE**: As the new marketplace app SDK release is required, so version bump will be done later.

### CODE REVIEW

**Review by cs-raj — APPROVED** [review]

**Comment by shafeeqd959** [comment]
@antonyagustine , can you bump the version ?

**Comment by antonyagustine** [comment]
> @antonyagustine , can you bump the version?

@shafeeqd959 Please check the NOTE mentioned in the descriptions.

**Comment by shafeeqd959** [comment]
@antonyagustine , got it. If this is dependent on sdk team, then its better to keep this as a draft PR.

**Comment by shafeeqd959** [comment]
@antonyagustine , got it. Is new marketplace app sdk released ?

**Comment by antonyagustine** [comment]
> @antonyagustine , got it. Is new marketplace app sdk released ?

Not yet

**Comment by shafeeqd959** [comment]
@antonyagustine , pls keep it as a draft PR

**Pull request merged**
