### PR TITLE
Bugfix/CS-38941

### PR DESCRIPTION
**Pull request by cs-raj**
Ticket: CS-38941
Version: 1.0.7

### CODE REVIEW

**Comment by netrajpatel** [comment]
@cs-raj 
Add ticket number and version bump info in PR, and also add PR link in the ticket.

**Comment by cs-raj** [comment]
> @cs-raj Add ticket number and version bump info in PR, and also add PR link in the ticket.

Yes, I will add it

**Review by netrajpatel — APPROVED** [review]

**Comment by netrajpatel** [comment]
@cs-raj This PR has conflicts with latest development code, please resolve that.

**Comment by cs-raj** [comment]
Merged the latest development changes into the branch

**Review by netrajpatel — APPROVED** [review]

**Pull request merged**
