### PR TITLE
Fix/cs 28220

### PR DESCRIPTION
**Pull request by abhinav-from-contentstack**

### CODE REVIEW

**Comment by abhinav-from-contentstack** [comment]
okay @netrajpatel, let me check that

**Comment by abhinav-from-contentstack** [comment]
Hi @netrajpatel, I have added the sonarlint fix

**Comment by shafeeqd959** [comment]
@abhinav-from-contentstack , lets connect on this PR 
CC: @netrajpatel

**Comment by abhinav-from-contentstack** [comment]
> @abhinav-from-contentstack Can you please run sonar scan and resolve sonar issues if any?

Hi @netrajpatel, I have added the sonarlint fix

**Pull request merged**
